//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_info
    {
        public int Emp_id { get; set; }
        public int Personal_id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public System.DateTime Hired_date { get; set; }
        public System.DateTime End_date { get; set; }
        public string Address { get; set; }
        public string Phone_ { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
    }
}
